<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img slot1</name>
   <tag></tag>
   <elementGuidId>9ee3b4ce-f7b2-431d-b2e7-a9838ba5f1e6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//img[@alt='ArrowDown'])[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img[alt=&quot;ArrowDown&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[data-testid=&quot;slot-slot1-species-dropdown&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>36c30864-16e1-47f6-b574-a8e3d976c69b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>data:image/svg+xml,%3csvg%20xmlns='http://www.w3.org/2000/svg'%20width='33'%20height='18'%20viewBox='0%200%2033%2018'%20fill='none'%3e%3cpath%20d='M0%200L16.5%2018L33%200H0Z'%20fill='%2378104F'/%3e%3c/svg%3e</value>
      <webElementGuid>1ab105e4-caaf-4d30-b58c-22422207fb2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>ArrowDown</value>
      <webElementGuid>538f1deb-48b5-4f8d-985b-aee8e6d541ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;w-full h-full&quot;]/div[@class=&quot;relative&quot;]/div[@class=&quot;gradient&quot;]/div[@class=&quot;flex flex-row py-5 h-auto justify-center mx-auto&quot;]/div[@class=&quot;absolute left-1/2 transform -translate-x-1/2 top-[33%] flex flex-col justify-center items-center w-full md:w-full md:h-[47vh] lg:max-w-full lg:h-[52vh]
        transition-transform duration-500 ease-in-out  py-6 rounded-lg&quot;]/div[@class=&quot;flex flex-col px-4 w-[100%] md:w-[95%] lg:w-[100%] h-[50vh] md:h-[45vh] lg:h-[50vh] md:px-8&quot;]/div[@class=&quot;flex flex-row justify-center p-4 gap-10&quot;]/div[@class=&quot;flex flex-col w-full&quot;]/div[@class=&quot;flex flex-col justify-start items-start h-[40vh] md:h-[37vh] lg:h-[48vh] w-full bg-primary p-4 md:p-10  gap-2.5 md:gap-[3.4rem] lg:gap-4&quot;]/div[@class=&quot;mb-2 w-full lg:mb-6&quot;]/div[@class=&quot;relative w-full&quot;]/button[@class=&quot;px-4 py-4 border cursor-pointer flex items-center transition-all
          text-left
          md:text-[26px] w-full
         placeholder:text-black   text-black
         
         bg-tertiary&quot;]/img[1]</value>
      <webElementGuid>8d46f209-8487-4b24-8908-ae493282e4d5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div[2]/div/div/div[2]/div/div/div[4]/div/button/img</value>
      <webElementGuid>701558e2-dd32-4a5d-a7d5-3e6ce8880468</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='ArrowDown']</value>
      <webElementGuid>cc08f4b8-f12f-41ce-aadb-bbbdcf9fe0db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/button/img</value>
      <webElementGuid>c82b8bfc-9596-4f9a-b15b-16b7bf79a7c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = concat(&quot;data:image/svg+xml,%3csvg%20xmlns=&quot; , &quot;'&quot; , &quot;http://www.w3.org/2000/svg&quot; , &quot;'&quot; , &quot;%20width=&quot; , &quot;'&quot; , &quot;33&quot; , &quot;'&quot; , &quot;%20height=&quot; , &quot;'&quot; , &quot;18&quot; , &quot;'&quot; , &quot;%20viewBox=&quot; , &quot;'&quot; , &quot;0%200%2033%2018&quot; , &quot;'&quot; , &quot;%20fill=&quot; , &quot;'&quot; , &quot;none&quot; , &quot;'&quot; , &quot;%3e%3cpath%20d=&quot; , &quot;'&quot; , &quot;M0%200L16.5%2018L33%200H0Z&quot; , &quot;'&quot; , &quot;%20fill=&quot; , &quot;'&quot; , &quot;%2378104F&quot; , &quot;'&quot; , &quot;/%3e%3c/svg%3e&quot;) and @alt = 'ArrowDown']</value>
      <webElementGuid>0c184db2-7925-45db-8af4-0ab7fde75332</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
