<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>//svg[@data-icon='clock']/following-sibling::text()[normalize-space(.)='Checking...']/parent::div</description>
   <name>Checking</name>
   <tag></tag>
   <elementGuidId>2c3a624e-594b-4876-ab1c-44dd46cccc3d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[normalize-space(.)='Checking...']</value>
      </entry>
      <entry>
         <key>BASIC</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
