<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Are you confirming that you want to can_bcb4a5</name>
   <tag></tag>
   <elementGuidId>ec3bb9aa-ac00-4bc8-a3a0-f9cbd5c7cf53</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = 'Are you confirming that you want to cancel the following test(s)?SlotAccession noPet name1111charli2777jerry' or . = 'Are you confirming that you want to cancel the following test(s)?SlotAccession noPet name1111charli2777jerry')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div[4]/div/div[3]/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.overflow-x-auto</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Are you confirming that you want to cancel the following test(s)?SlotAccession n&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>52ef46d2-5b3d-47f9-905d-50706ef63543</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>overflow-x-auto</value>
      <webElementGuid>2b2429fd-45ce-4e65-a584-6a4fd560c05d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Are you confirming that you want to cancel the following test(s)?SlotAccession noPet name1111charli2777jerry</value>
      <webElementGuid>17732e8b-2bcf-4f2b-af18-12a225157572</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;gradient&quot;]/div[@class=&quot;fixed inset-[-600px] bg-black bg-opacity-60 flex items-center justify-center z-[2000]&quot;]/div[@class=&quot;bg-tertiary rounded-lg shadow-lg w-[20%] md:w-[26%] max-w-[28%] h-fit min-h-[18vh] max-h-[30vh] p-6 md:p-16&quot;]/div[@class=&quot;text-center text-[10px] mb-5 md:text-standard sm:text-[10px] md:h-auto&quot;]/div[@class=&quot;overflow-x-auto&quot;]</value>
      <webElementGuid>f8c83462-f51f-4ff2-9da9-1cea167ed481</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[4]/div/div[3]/div</value>
      <webElementGuid>27978dda-b93b-4431-8171-4737774f7662</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Confirm to cancel'])[1]/following::div[2]</value>
      <webElementGuid>2cee0592-1666-4aff-916a-03c629980194</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CANCEL'])[1]/following::div[6]</value>
      <webElementGuid>f838cc4b-d50d-4060-9e02-8dc29992cbb0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[3]/div</value>
      <webElementGuid>fa27f9a3-5aea-4a75-a740-f2551c6b599b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Are you confirming that you want to cancel the following test(s)?SlotAccession noPet name1111charli2777jerry' or . = 'Are you confirming that you want to cancel the following test(s)?SlotAccession noPet name1111charli2777jerry')]</value>
      <webElementGuid>fafa07bc-b475-4a35-86f0-852e2c2cdca6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
