<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_5.1-8.5</name>
   <tag></tag>
   <elementGuidId>fc86015c-c752-4b78-90f9-62f2ba290b7c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div[3]/div[2]/div/div/div[3]/div/div/div/div[2]/div/p[4]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;5.1-8.5&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>a4021d16-e8be-426a-a31f-b912b4dafa06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>flex-1 text-start</value>
      <webElementGuid>fca35193-d5b9-41f7-aa4c-4789d09c1899</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>5.1-8.5</value>
      <webElementGuid>1997169e-cd92-4a65-b730-43adde09366c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;gradient&quot;]/div[@class=&quot;fixed w-[580px] top-[172px] left-[10px]&quot;]/div[@class=&quot;modal-overlay&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;flex flex-col p-4&quot;]/div[@class=&quot;flex flex-row w-full&quot;]/div[@class=&quot;w-2/3 p-2&quot;]/div[@class=&quot;w-[353px] mt-[10px]&quot;]/div[@class=&quot;w-[353px] h-[508px] bg-white border overflow-hidden&quot;]/div[@class=&quot;overflow-y-auto max-h-[480px] pb-2&quot;]/div[@class=&quot;flex text-blue-600 font-bold p-2 ml-2&quot;]/p[@class=&quot;flex-1 text-start&quot;]</value>
      <webElementGuid>fb377a11-2b6c-49db-8a56-b2be334b6237</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[3]/div[2]/div/div/div[3]/div/div/div/div[2]/div/p[4]</value>
      <webElementGuid>4eda3a5f-4b3d-4752-a1df-29897e49cfb5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='EDIT'])[1]/following::p[17]</value>
      <webElementGuid>04070a8c-91b8-4376-b33f-d5f8121e2e8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NA'])[89]/following::p[17]</value>
      <webElementGuid>9ba51e07-e018-41a8-822b-5578bfb78d04</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='5.1-8.5']/parent::*</value>
      <webElementGuid>093c20ca-1e79-47e1-93ba-64e043daea6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/p[4]</value>
      <webElementGuid>aa239503-2db3-4d9b-95b1-cc615aa368c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = '5.1-8.5' or . = '5.1-8.5')]</value>
      <webElementGuid>bc776c8e-9517-4657-aa4e-dde78d3ac8a5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
