<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_SETTINGS</name>
   <tag></tag>
   <elementGuidId>3ca0e5a4-2480-44fd-a264-885dc0ce92a6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div/button</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;SETTINGS&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>b38ecf9f-8eb2-42e6-91c5-858b13f87e73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>bg-white border-none w-[9rem] h-[2.25rem] md:w-[17.125rem] md:h-[4.25rem] rounded-full text-xs md:text-tiny font-semibold </value>
      <webElementGuid>7d11bc39-54c5-41e8-9a9c-7dc6ad21c4c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>SETTINGS</value>
      <webElementGuid>ea854b2d-3b30-4d95-9a07-33b7a0a90fca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;gradient&quot;]/div[@class=&quot;fixed bottom-[1%] left-1/2 transform -translate-x-1/2 w-full flex justify-center items-center h-[12vh] flex flex-col p-6 md:p-12&quot;]/div[@class=&quot;flex justify-between items-center w-full mb-[10px] md:w-full md:h-full justify-between&quot;]/button[@class=&quot;bg-white border-none w-[9rem] h-[2.25rem] md:w-[17.125rem] md:h-[4.25rem] rounded-full text-xs md:text-tiny font-semibold&quot;]</value>
      <webElementGuid>fdb28840-3bc4-4af8-842b-4e134f7e684d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/button</value>
      <webElementGuid>b2b7c9cc-2758-4c6a-8218-dfe82567dce8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MAINTENANCE'])[1]/following::button[1]</value>
      <webElementGuid>d8ae3f30-9ce1-49db-95ba-63bb425e4f74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AlphaCyte'])[1]/following::button[2]</value>
      <webElementGuid>24256049-2db5-4842-b1c8-6d99dbe02744</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='HISTORY'])[1]/preceding::button[1]</value>
      <webElementGuid>c591e054-fe4c-471a-ad32-1f45c4df3d3f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Enter order details'])[1]/preceding::button[2]</value>
      <webElementGuid>46528bfa-a7cb-44e3-a110-e117f45a8a11</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='SETTINGS']/parent::*</value>
      <webElementGuid>4e165558-83ec-4014-8f05-4132dc0c06ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/button</value>
      <webElementGuid>c882009b-9d7d-4ad2-a1c1-68b864faad0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'SETTINGS' or . = 'SETTINGS')]</value>
      <webElementGuid>b50ed239-872b-43a3-838f-d82876d20ace</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
