<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_CLOSE</name>
   <tag></tag>
   <elementGuidId>7c8c0b1e-1f22-4608-9042-46fbcb1c3557</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div[2]/div[4]/button</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;CLOSE&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>a2fec050-90ab-41bf-91dc-8d8a1e71a231</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>bg-white border-none w-[9rem] h-[2.25rem] md:w-[17.125rem] md:h-[4.25rem] rounded-full text-xs md:text-tiny font-semibold </value>
      <webElementGuid>8abac3f6-364b-450c-a449-77652173b503</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>CLOSE</value>
      <webElementGuid>323d91d2-40bd-4ae0-a923-eb302d1571d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;gradient&quot;]/div[@class=&quot;w-[95%] h-[80vh]  bg-primary p-8 md:p-16 md:m-10&quot;]/div[@class=&quot;fixed bottom-[40px] left-1/2 transform -translate-x-1/2&quot;]/button[@class=&quot;bg-white border-none w-[9rem] h-[2.25rem] md:w-[17.125rem] md:h-[4.25rem] rounded-full text-xs md:text-tiny font-semibold&quot;]</value>
      <webElementGuid>a675ba54-bf1f-485f-84ba-83ef9405fdf3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div[4]/button</value>
      <webElementGuid>fb6e28b0-e80c-45f6-80b6-771baeaefd5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SAVE'])[1]/following::button[1]</value>
      <webElementGuid>8d3ceaba-09ad-4a6d-bb0e-02b9860e9000</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='RESET TO DEFAULT'])[1]/following::button[2]</value>
      <webElementGuid>bcfb77da-c2bd-43b6-a0c1-766017c37e58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='CLOSE']/parent::*</value>
      <webElementGuid>e8376ed7-8a65-49cc-a6bd-39a76c852dab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/button</value>
      <webElementGuid>eeb93a31-627d-48bb-b2ee-97d04519c300</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'CLOSE' or . = 'CLOSE')]</value>
      <webElementGuid>a0fd37c8-d472-47c8-bdd3-8ac1be5e6868</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
