<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Feline</name>
   <tag></tag>
   <elementGuidId>0e4c5902-4ee8-4448-bdcd-7091c22bd6bf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div[2]/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Feline&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>4803c9de-f42b-401f-8ec4-92ca31a7c48c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>px-4 py-2 border cursor-pointer rounded-md transition-all duration-300 md:text-[26px] bg-white h-[4vh]</value>
      <webElementGuid>aa9459fa-84bc-494b-8a67-a6bd7996a6f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Feline</value>
      <webElementGuid>4d026c6c-cd2c-4230-ac34-e0480119e1b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;gradient&quot;]/div[@class=&quot;w-[95%] h-[80vh]  bg-primary p-8 md:p-16 md:m-10&quot;]/div[@class=&quot;relative w-full z-[100]&quot;]/div[@class=&quot;px-4 py-2 border cursor-pointer rounded-md transition-all duration-300 md:text-[26px] bg-white h-[4vh]&quot;]</value>
      <webElementGuid>98a305dd-94b1-4066-bfe8-4a1b249d7c7f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div/div</value>
      <webElementGuid>d19d5edf-8c35-4b0d-a528-6f0fc3c5fa20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reference range'])[1]/following::div[2]</value>
      <webElementGuid>9f4d539b-98f9-4b0b-bca4-f10c4abae094</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AlphaCyte'])[1]/following::div[9]</value>
      <webElementGuid>7812835c-f644-449f-b09a-aa50c70a8a3b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='RESET TO DEFAULT'])[1]/preceding::div[63]</value>
      <webElementGuid>caab996f-1060-403d-9890-7627dded6b5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SAVE'])[1]/preceding::div[63]</value>
      <webElementGuid>ddca54f8-4506-4cf6-ba9a-cce7bb026dae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Feline']/parent::*</value>
      <webElementGuid>b24ebf8a-c688-4166-af98-4ac08d01e412</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div</value>
      <webElementGuid>b5b112b6-3f51-4808-9e7e-d9b48ad3cce0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Feline' or . = 'Feline')]</value>
      <webElementGuid>f2ed14f5-81c8-45a1-b1b1-032e3ca16663</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
