<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Canine_w-74px h-30px text-start mdpl-_b88416</name>
   <tag></tag>
   <elementGuidId>670e2cb0-1cb0-4b98-935c-2beb8f7790f0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='7.89']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>div >> internal:has-text=/^RBC10\^12/L$/ >> internal:role=textbox >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>31c127e3-e7af-4b8b-837f-83c28642dfe9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>0a35a8a2-9f38-4e6a-ab9c-1a073eccf332</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-[74px] h-[30px] text-start md:pl-4 border  z-1 md:w-[85%] md:h-[3vh] border-gray-300</value>
      <webElementGuid>2e135eb4-318a-429c-bad2-25c23f157cb4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>7.89</value>
      <webElementGuid>5d926975-94b0-4a9c-8558-bbce8331d77b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;gradient&quot;]/div[@class=&quot;w-[95%] h-[80vh]  bg-primary p-8 md:p-16 md:m-10&quot;]/div[@class=&quot;w-full h-[75%] bg-white border mt-5 overflow-y-auto md:h-[80%] md:mt-10&quot;]/div[@class=&quot;grid grid-cols-4 items-center p-1 gap-4 text-sm md:text-standard md:p-6&quot;]/div[@class=&quot;relative flex justify-start items-start&quot;]/input[@class=&quot;w-[74px] h-[30px] text-start md:pl-4 border  z-1 md:w-[85%] md:h-[3vh] border-gray-300&quot;]</value>
      <webElementGuid>80710eee-e877-4ab0-87cb-bff2587d52fa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='7.89']</value>
      <webElementGuid>53b5bb6f-a222-4baf-acc5-c45d27e629ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div[2]/div[2]/div/input</value>
      <webElementGuid>e07ef062-5dcd-4296-a01b-99fccdf0f09b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>20696196-471d-46d2-9fd5-2e3557ac34aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text']</value>
      <webElementGuid>30ea66ea-9c32-4223-b5a6-f5987b2afa0e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
